import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import React, { useEffect, useState } from 'react'
import { Inter } from 'next/font/google'
import { DropDown } from '@/components/DropDown'
import styles from '@/styles/Home.module.css'
import { T_Data } from './api/hello'
import { ICheckboxCommon } from '@/components/Checkbox'
import { IAllPriceData } from '@/interface'
import { ScatterGraph } from '@/components/Chart/Scatter';
import { BubbleGraph } from '@/components/Chart/Bubble'
import { Checkbox, MultiCheckbox } from "@/components/Checkbox"


interface IRegion {
  data: T_Data[]
}

export default function Home() {
  const [citys, setCitys] = useState<string[]>([])
  const [region, setRegion] = useState<IRegion>({ data: [] })
  const [selectCity, setSelectCity] = useState<string>("台北市")
  const [selectRegion, setSelectRegion] = useState<string>('')
  const [checkboxRegion, setCheckboxRegion] = useState<ICheckboxCommon[]>([])
  const [checkboxDataMap, setCheckboxDataMap] = useState(new Map())
  const [allPriceData, setAllPriceData] = useState<IAllPriceData[]>([])
  const [selectPriceData, setSelectPriceData] = useState<IAllPriceData[]>([])

  const handleChangeCity = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectCity(e.target.value)
  }
  const handleChangeRegion = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setSelectRegion(e.target.value)
  }

  // checkbox new set
  const handelCheckboxMap = (value: string) => {
    if (checkboxDataMap.has(value)) {
      const cloneMap = new Map([...checkboxDataMap])
      cloneMap.delete(value)
      return setCheckboxDataMap(cloneMap)
    }
    const specificData = allPriceData.filter((val) => {
      return val.address.indexOf(value) > -1
    })
    const newMap = new Map<string, IAllPriceData[]>([[value, specificData]])
    setCheckboxDataMap((prev) => new Map([...prev, ...newMap]))
  }

  // mock region data
  useEffect(() => {
    (async () => {
      const fetchData = await fetch('/api/hello')
      const data = await fetchData.json()
      const citys = data.data.map((val: { city: string }) => {
        return val.city
      })
      setCitys(citys)
      setRegion(data)
    })()
  }, [])

  //get data 
  useEffect(() => {
    (async () => {
      const fetchData = await fetch('http://localhost:3050/getPrice')
      const data = await fetchData.json()
      setAllPriceData(data.data)
    })()
  }, [])
  // filter region
  useEffect(() => {
    const regionFilter = allPriceData.filter((data: IAllPriceData) => {
      return data.address.indexOf(selectRegion) > -1
    })
    setSelectPriceData(regionFilter)
  }, [selectRegion])
  // checkbox region filter
  useEffect(() => {
    if (region.data.length > 0) {
      const regions = region.data.filter((val: { city: string }) => {
        return val.city === selectCity
      })
      const checkboxData = regions[0].region.map((val: string) => {
        return {
          name: val,
          child: val,
          value: val
        }
      })
      setCheckboxRegion(checkboxData)
    }
  }, [citys])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.9.1/chart.min.js" integrity="sha512-ElRFoEQdI5Ht6kZvyzXhYG9NqjtkmlkfYk0wr6wHxU9JEHakS7UJZNeml5ALk+8IKlU6jDgMabC3vkumRokgJA=="></Script>
        <Script src="https://cdn.jsdelivr.net/npm/moment@^2"></Script>
        <Script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@^1"></Script>
      </Head>
      <main className={styles.main}>
        <MultiCheckbox dataArr={checkboxRegion} handleCheckbox={handelCheckboxMap} />
        <div>
          {
            citys.length > 0 && <DropDown value={citys} defaultSelect={selectCity} handleCallback={handleChangeCity} />
          }
          {
            region && region.data && region?.data.map((val) => {
              return selectCity === val.city && <DropDown value={val.region} handleCallback={handleChangeRegion} />
            })
          }
        </div>

        {/* <ScatterGraph data={selectPriceData} /> */}
        <BubbleGraph data={Array.from(checkboxDataMap)} />
      </main>
    </>
  )
}
